
EXEC sp_resetstatus [IMMBR1]

ALTER DATABASE [IMMBR1] SET EMERGENCY

DBCC CHECKDB([IMMBR1])
/*
ALTER DATABASE [IMMBR1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

DBCC CHECKDB ([IMMBR1], REPAIR_ALLOW_DATA_LOSS)

ALTER DATABASE [IMMBR1] SET MULTI_USER
*/