-- runs as SQLCMD Mode
:Connect BY-SPBBS02\BBS02
USE [master]
GO
BACKUP DATABASE [EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1]
 TO  DISK = N'\\BY0NA0\BackupRestore2\EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1.bak' WITH  COPY_ONLY, FORMAT, INIT, COMPRESSION, STATS = 5
GO
:Connect BY-SP2K13MP01\MP01
RESTORE DATABASE [EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1]
 FROM  DISK = N'\\BY0NA0\BackupRestore2\EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1.bak' WITH  COPY_ONLY, NORECOVERY,  NOUNLOAD, STATS = 5
GO
:Connect BY-SPBBS02\BBS02
BACKUP LOG [EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1]
 TO  DISK = N'\\BY0NA0\BackupRestore2\EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1.trn' WITH COPY_ONLY, FORMAT, INIT, COMPRESSION, STATS = 5
GO
:Connect BY-SP2K13MP01\MP01
RESTORE LOG [EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1]
 FROM  DISK = N'\\BY0NA0\BackupRestore2\EMCOBBSPROD_MSS_ManagedMetadataServiceDB_BBS1_D_1.trn' WITH COPY_ONLY, STATS = 5 --, NORECOVERY
GO

