-- Needs to be in SQLCMD Mode!!
-- Andrew Craven, 2014-2105
:connect by-gdcsql056\gdc056
BACKUP DATABASE [WSS_Content_BAG_01] TO  DISK = N'\\BY-SPDATA01\Share01\WSS_Content_BAG_01.BAK' WITH  COPY_ONLY, NOFORMAT, INIT,  NAME = N'WSS_Content_BAG_01-Vollständig Datenbank Sichern', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
--BACKUP DATABASE [WSS_Content_BAG_01] TO  DISK = N'\\BY-SPDATA01\Share01\WSS_Content_BAG_01.BAK' WITH  NOFORMAT, INIT,  NAME = N'WSS_Content_BAG_01-Vollständig Datenbank Sichern', SKIP, NOREWIND, NOUNLOAD,  STATS = 5
GO
BACKUP LOG [WSS_Content_BAG_01] TO  DISK = N'\\BY-SPDATA01\Share01\WSS_Content_BAG_01.TRN' WITH  COPY_ONLY, NOFORMAT, INIT,  NAME = N'WSS_Content_BAG_01-TLog Sichern', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
:connect BY-SPDATA01\SPDATA01
RESTORE DATABASE [WSS_Content_BAG_01] FROM  DISK = N'E:\Data_01\Shares\Share01\WSS_Content_BAG_01.BAK' WITH  FILE = 1,  MOVE N'WSS_Content_BAG_01' TO N'E:\Data_01\Data\WSS_Content_BAG_01.mdf',  MOVE N'WSS_Content_BAG_01_log' TO N'E:\Tlog_01\Tlog\WSS_Content_BAG_01_log.LDF',  NORECOVERY,  NOUNLOAD,  STATS = 5
GO
RESTORE LOG [WSS_Content_BAG_01] FROM  DISK = N'E:\Data_01\Shares\Share01\WSS_Content_BAG_01.TRN' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  STATS = 5
GO
ALTER DATABASE [WSS_Content_BAG_01] SET PARTNER = 'TCP://by-gdcsql056.de.bayer.cnb:5023'
GO
:connect by-gdcsql056\gdc056
ALTER DATABASE [WSS_Content_BAG_01] SET PARTNER = 'TCP://BY-SPDATA01.de.bayer.cnb:5022'
GO
ALTER DATABASE [WSS_Content_BAG_01] SET SAFETY OFF
GO
:connect BY-SPDATA01\SPDATA01
!!DEL \\BY-SPDATA01\E$\Data_01\Shares\Share01\WSS_Content_BAG_01.*
--!!DIR \\BY-SPDATA01\E$\Data_01\Shares\Share01